# Cloud Build configuration for automatic Cloud Run deployment
# This file is used when you set up a Cloud Build trigger
# Triggered on: push to main branch

steps:
  # Step 1: Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/log-simulator:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/log-simulator:latest'
      - '.'
    id: 'build-image'

  # Step 2: Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/log-simulator:$COMMIT_SHA'
    id: 'push-image'

  # Step 3: Push the latest tag
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/log-simulator:latest'
    id: 'push-latest'

  # Step 4: Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'log-simulator'
      - '--image'
      - 'gcr.io/$PROJECT_ID/log-simulator:$COMMIT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '512Mi'
      - '--cpu'
      - '1'
      - '--min-instances'
      - '0'
      - '--max-instances'
      - '10'
      - '--timeout'
      - '300'
      - '--set-env-vars'
      - 'LOG_SIM_RATE_LIMIT_ENABLED=true,LOG_SIM_MAX_LOG_COUNT=10000'
    id: 'deploy-cloud-run'

# Store images in Container Registry
images:
  - 'gcr.io/$PROJECT_ID/log-simulator:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/log-simulator:latest'

# Build options
options:
  machineType: 'N1_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY

# Timeout for entire build
timeout: '1200s'
